#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${ZITADEL_POSTGRES_USER} WITH PASSWORD '${ZITADEL_POSTGRES_PASSWORD}';
    CREATE DATABASE ${ZITADEL_POSTGRES_DB} OWNER ${ZITADEL_POSTGRES_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${ZITADEL_POSTGRES_DB} TO ${ZITADEL_POSTGRES_USER};
EOSQL